DefaultContentLanguage = "es"
author = "Roberto Rodríguez"
baseURL = "https://www.rrodriguze.es/"
copyright = "Copyright © 2020, Steve Francia and the Hugo Authors; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "es"
paginate = 3
theme = "casper3"
title = "Blog de Roberto"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "author"
name = "Author Homepage"
url = "https://jonathanjanssens.com"
weight = 40
[params]
description = "Blog personal donde voy a escribir sobre las cosillas que vaya aprendiendo del mundo de la programación."
facebook = ""
github = "https://github.com/rrodriguze"
logo = "/images/ghost-transparent.png"
mainSections = ["post"]
twitter = "https://twitter.com/roberto96rr"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
